=== NeilMoras/Ticket_System/xml/ticket.xsd
<?xml version="1.0" encoding="utf-8"?>
  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="tickets">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="ticket" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element name="subject" type="xs:string"/>
            <xs:element name="datetime" type="xs:dateTime"/>
            <xs:element name="messages">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="message" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                      <xs:simpleContent>
                        <xs:extension base="xs:string">
                          <xs:attribute name="senderid" type="xs:positiveInteger" use="required"/>
                          <xs:attribute name="timestamp" type="xs:dateTime" use="required"/>
                        </xs:extension>
                      </xs:simpleContent>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="userid"  type="xs:positiveInteger" use="required"/>
          <xs:attribute name="ticketid" type="xs:positiveInteger" use="required"/>
          <xs:attribute name="status" type="statuscode" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:simpleType name="statuscode">
  <xs:restriction base="xs:string">
    <xs:enumeration value="resolved"/>
    <xs:enumeration value="ongoing"/>
  </xs:restriction>
</xs:simpleType>
</xs:schema>

=== NeilMoras/Ticket_System/xml/ticket.xml
<?xml version="1.0" encoding="utf-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ticket.xsd">
  <!-- There can be only one subject -->
  <!-- There can be more than one message -->
  <!-- There can be only one date time -->
  <ticket userid="61" ticketid="2" status="resolved">
    <subject>Wrong item delivered</subject>
    <datetime>2020-02-01T03:45:59</datetime>
    <messages>
      <message senderid="61" timestamp="2020-02-01T03:45:59">Hello, I have been Delivered a wrong item, it was meant to be a rice cooker but got delivered an air fryer instead</message>
      <message senderid="34" timestamp="2020-02-02T03:35:59">Sorry to hear that, we will definitley they it replaced.</message>
      <message senderid="61" timestamp="2020-02-02T04:53:59">Thank you, can i get a refund instead</message>
      <message senderid="34" timestamp="2020-02-03T16:45:59">Definitely, we would like you to fill up a form sent to your email inorder to send us back the item and we will refund you immediately</message>
      <message senderid="61" timestamp="2020-02-03T16:45:59">Definitely, we would like you to fill up a form sent to your email inorder to send us back the item and we will refund you immediately</message>
    </messages>
  </ticket>
  <ticket userid="61" ticketid="3" status="ongoing">
    <subject>Refund</subject>
    <datetime>2020-02-04T16:32:14</datetime>
    <messages>
      <message senderid="61" timestamp="2020-02-03T03:45:45">Hello, I have been Delivered a wrong item, it was meant to be a rice cooker but got delivered an air fryer instead</message>
      <message senderid="34" timestamp="2020-02-04T10:45:04">Sorry to hear that, we will definitley they it replaced.</message>
      <message senderid="61" timestamp="2020-02-04T16:54:59">Thank you, can i get a refund instead</message>
      <message senderid="34" timestamp="2020-02-05T18:15:59">Definitely, we would like you to fill up a form sent to your email inorder to send us back the item and we will refund you immediately</message>
      <message senderid="34" timestamp="2021-09-19T00:34:56">hryre</message></messages>
  </ticket>
  <ticket userid="83" ticketid="5" status="resolved">
    <subject>My Item is Broken within few months of purchase</subject>
    <datetime>2020-02-04T16:32:14</datetime>
    <messages>
      <message senderid="83" timestamp="2020-02-03T03:45:45">Hello, I have been Delivered a wrong item, it was meant to be a rice cooker but got delivered an air fryer instead</message>
      <message senderid="34" timestamp="2020-02-04T10:45:04">Sorry to hear that, we will definitley they it replaced.</message>
      <message senderid="83" timestamp="2020-02-04T16:54:59">Thank you, can i get a refund instead</message>
      <message senderid="34" timestamp="2020-02-05T18:15:59">Definitely, we would like you to fill up a form sent to your email inorder to send us back the item and we will refund you immediately</message>
      </messages>
  </ticket>
  <ticket userid="83" ticketid="6" status="ongoing">
    <subject>Not Happy with Service</subject>
    <datetime>2021-02-04T18:32:14</datetime>
    <messages>
      <message senderid="83" timestamp="2020-02-03T04:45:45">Hello, I am not happy with the recent product i purchased</message>
      <message senderid="34" timestamp="2020-02-04T12:45:04">Sorry to hear that, we will definitley they it replaced.</message>
      <message senderid="83" timestamp="2020-02-04T17:54:59">Thank you, can i get a refund instead</message>
      <message senderid="34" timestamp="2020-02-05T18:15:59">Definitely, we would like you to fill up a form sent to your email inorder to send us back the item and we will refund you immediately</message>
<message senderid="34" timestamp="2021-09-19T00:43:23">dfadf</message></messages>
  </ticket>
  <ticket userid="61" ticketid="105" status="ongoing">
    <subject>i am angry</subject>
    <datetime>2021-09-18T18:51:46</datetime>
    <messages>
      <message senderid="61" timestamp="2021-09-18T18:51:46">HELLO mIKE TESTING 1 2 3</message>
    <message senderid="34" timestamp="2021-09-18T15:21:01">Yo</message>
    <message senderid="34" timestamp="2021-09-18T15:21:57"> white white</message>
    <message senderid="34" timestamp="2021-09-18T15:22:24">fasfasfas</message><message senderid="34" timestamp="2021-09-19T00:37:00">gdfg</message><message senderid="34" timestamp="2021-09-19T00:50:14">hry</message><message senderid="34" timestamp="2021-09-19T00:50:50">hry</message><message senderid="34" timestamp="2021-09-19T00:51:13">yo</message><message senderid="34" timestamp="2021-09-19T00:51:26">yo</message><message senderid="34" timestamp="2021-09-19T00:52:54">yo</message><message senderid="34" timestamp="2021-09-19T00:53:03">sdfsd</message></messages>
  </ticket>
<preserveWhiteSpace/><formatOutput>1</formatOutput></tickets>
