=== NeilMoras/Ticket_System/xml/user.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:positiveInteger"/>
              <xs:element name="username" type="xs:string"/>
              <xs:element name="staffId" type="staffids" minOccurs="0"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="password" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="accountType" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="staffids">
    <xs:restriction base="xs:token">
      <xs:pattern value="[n/N]{1}\d+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== NeilMoras/Ticket_System/xml/user.xml
<?xml version="1.0" encoding="utf-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="user.xsd">
  <!-- Login with user and admin -->
  <user accountType="client">
    <id>61</id>
    <username>neilmoras</username>
    <email>neil.j@yahoo.com</email>
     <password>$2y$10$I/cPIcq.wpOD5RrDX8pof.YLs9rET1r3KRlsg7v0dn9GZDKsigXEy</password>
    <!-- xml5203 -->
  </user>
  <user accountType="admin">
    <id>34</id>
    <username>johndoe</username>
    <staffId>N12345</staffId>
    <email>user@hotmail.com</email>
    <password>$2y$10$KOHvIL44hE.HDnunIVQVH.TfaO0nt3a3hh4bdGUqSBJq6csBcJCTm</password>
    <!-- xmldom5203 -->
  </user>
<user accountType="client">
  <id>83</id>
  <username>neil</username>
  <email>neilmoras@gmail.com</email>
  <password>$2y$10$sJdxqxsbNnK7k2lNkwS.NeQHW1gt3d4DGQzv6ZyK7CnXIySIdrb0C</password>
  <!-- johndoe123 -->
</user>
</users>
